### ISSUE TITLE
Training masked_lm task

### ISSUE THREAD

**Issue by kristjanArumae** [pytorch/fairseq#1240]
I followed the instructions from this README:
https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md

I get a TypeError when I run the fairseq-train command as listed.  The changes I made to the inputs were to account for less GPU RAM, but otherwise remained the same.  Here is the stacktrace:

-- Process 6 terminated with the following error:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/fairseq/fairseq_cli/train.py", line 290, in distributed_main
    main(args, init_distributed=True)
  File "/home/fairseq/fairseq_cli/train.py", line 70, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/fairseq/fairseq/checkpoint_utils.py", line 123, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(epoch=itr_state['epoch'], load_dataset=True, data_selector=data_selector)
  File "/home/fairseq/fairseq/trainer.py", line 236, in get_train_iterator
    data_selector=data_selector,
TypeError: load_dataset() got an unexpected keyword argument 'data_selector'

**Comment by ngoyal2707** [comment]
Thanks for flagging this, this seems to have recently broken in https://github.com/pytorch/fairseq/commit/b6e001f634a13ee216d4b496a2e39031e22ddecb#diff-62a99926a9ef727a976dd7351fb9ff7d . looking at fixing it

**Comment by DikshaMeghwal** [comment]
any idea by when can we expect for this to get fixed?

**Comment by louismartin** [comment]
Same problem here
